### PR TITLE
Deps remove

### PR DESCRIPTION
**Pull request by evilive3000**

### CODE REVIEW

**Review by gladiatortoise — COMMENTED** [review]
Is this not useful in some situations though? Just if the user wants to access the interface, but is lazy to check where it originates from.

**Comment by gladiatortoise** [comment]
This comment was meant to c2a7bd6

**Review by gladiatortoise — APPROVED** [review]

**Review by gladiatortoise — CHANGES_REQUESTED** [review]
This is a breaking change and probably unnecessary. Or what do you think?

**Comment by evilive3000** [comment]
Sorry, I'm a bit confused... did you change somethings? 
What breaking change you are talking about. Are you asking about Cookie Interface?

**Comment by gladiatortoise** [comment]
> Sorry, I'm a bit confused... did you change somethings?
> What breaking change you are talking about. Are you asking about Cookie Interface?

Hi! I'm only talking about this commit: https://github.com/gladiatortoise/node-apiless-youtube-upload/pull/13/commits/c2a7bd646af1fe87e0249f96e3376915b426237e

I have not changed anything yet.

**Comment by evilive3000** [comment]
ok, I just rechecked public interface of `YoutubeUploader` class and I don't see where user can or will passing the `IWebDriverCookie` interface. 

But even if you left this export it will not give any help to the user. Because this interface described in `@types/selenium-webdriver` but it is devDependency and will not be installed in the user's project.

**Comment by evilive3000** [comment]
image

Here is how my IDE react to this interface.

**Comment by gladiatortoise** [comment]
> ok, I just rechecked public interface of `YoutubeUploader` class and I don't see where user can or will passing the `IWebDriverCookie` interface. 
> 
> But even if you left this export it will not give any help to the user. Because this interface described in `@types/selenium-webdriver` but it is devDependency and will not be installed in the user's project. 

The interface is useful when using the methods exported in index.ts, like ```uploadVideo(videoObj, IWebDriverCookie[])```

But you're right, it's not even a dependency anymore, and changing that probably wouldn't make sense just for the interface. Or what do you think?

**Comment by gladiatortoise** [comment]
Actually, maybe it would be the best to move @types/selenium-webdriver to depencies. Or what do you think? 🤔

**Comment by evilive3000** [comment]
Maybe there is a way to mimic this interface so users don't have to pull extra deps, especially @types deps.
I will try to fix this tonight.

**Comment by gladiatortoise** [comment]
OK thank you!

**Comment by evilive3000** [comment]
Did not find a better solution, so I moved selenium-webdriver types from devDeps to Deps.

I don't think it's necessary to re-export it from the index file, all smart IDE should show the correct shape of cookie interface when you'll try to pass it into function.

**Comment by gladiatortoise** [comment]
> Did not find a better solution, so I moved selenium-webdriver types from devDeps to Deps.
> 
> I don't think it's necessary to re-export it from the index file, all smart IDE should show the correct shape of cookie interface when you'll try to pass it into function.

What do you think of this situation:

```typescript
var cookies = fs.readJSONSync('./cookies.json')
uploadVideo(videoObj, cookies) // type error
```
vs
```typescript
import {IWebDriverCookie} from 'node-apiless-youtube-upload'

var cookies = fs.readJSONSync('./cookies.json') as IWebDriverCookie[]
uploadVideo(videoObj, cookies) // everything good
```

**Comment by evilive3000** [comment]
I see your points. To be honest I have a gut feeling that this approach is something wrong :) but I can't say how to do it right now.

How user created the file `cookies.json`, how can we be sure that the stored structure is valid?
If user used our methods to save the file, then s/he must use our methods to read it.

Why you don't use `loadCookiesFromDisk`?

```ts
import loadCookiesFromDisk from './methods/loadCookiesFromDisk'
import uploadVideo, {VideoObj} from './methods/uploadVideo'

;(async () => {
    let videoObj: VideoObj = {...}
    const cookies = await loadCookiesFromDisk('path/to/cookies')
    await uploadVideo(videoObj, cookies)
})().catch(console.error)
```

**Comment by gladiatortoise** [comment]
> How user created the file `cookies.json`, how can we be sure that the stored structure is valid?
> If user used our methods to save the file, then s/he must use our methods to read it.

Right. Maybe a better example would be that a user wants to store and load cookies from a database. Or if cookies are received as JSON from other process, or whatever.

I understand now that it's not right to just assert it IWebDriverCookie[] blindly, although it solves the type error. So maybe there could be a function like ```asWebDriverCookies(cookies : any)``` that returns either false or IWebDriverCookie[]. 

This feels overly complicated but if you want to make your own cookie storing/loading system, this is a problem you will face.

**Comment by evilive3000** [comment]
Please check my last commit.
I got rid of any exports of IWebDriverCookies.
Created custom cookie class with static methods to cover all needs we talk earlier.

```ts
import {Cookies} from './helpers'

let cookies: Cookies

cookies = Cookies.fromJSONFileSync('path/to/file')
cookies = Cookies.fromJSONString('some-json-stored-cookies')

// you can iterate it
for (const cookie of cookies) console.log(cookie)

// you can check it's length
console.log(cookies.length);


```

**Comment by gladiatortoise** [comment]
Awesome 👍 I will test to make sure it doesn't break anything in a bit and then merge

**Comment by gladiatortoise** [comment]
Wait I don't see why you abandoned the methods ```loadCookiesFromDisk``` and ```saveCookiesToDisk``` in ```./methods```

**Comment by evilive3000** [comment]
I thought they are redundant, all their functionality now in class Cookie?
Do you need them for some other cases?

**Comment by gladiatortoise** [comment]
> I thought they are redundant, all their functionality now in class Cookie?
> Do you need them for some other cases?

Yeah they are redudant now because you basically rewrote them to cookies.ts. My existing code uses them so I don't think they should be removed just for appearances

**Comment by gladiatortoise** [comment]
Maybe they could return Cookies instance? What do you think

**Comment by evilive3000** [comment]
Do you mean code in `Usage` file or some external code?

**Comment by gladiatortoise** [comment]
> Do you mean code in `Usage` file or some external code?

I just mean my own app that uses this module.

**Comment by gladiatortoise** [comment]
> Do you mean code in `Usage` file or some external code?
> If you want I can modify the example. It's one line replacement.
> Can you modify your external code so we could make this lib not to depend on some invisible dependencies?
> 
> If it does not work for you I can return those methods.

I think every libarary is a bit dependent on mainatining a non-changing API, at least to some extent

**Comment by evilive3000** [comment]
Or you can stick with 1.1.19 version.
And bump new one 2.0.0, so it will mean breaking changes

**Comment by evilive3000** [comment]
ok, I'll return it, and update usage file

**Comment by gladiatortoise** [comment]
Usage and readme are fine with this, they don't import ./methods/saveCookiesToDisk.ts or loadCookiesToDisk

**Comment by gladiatortoise** [comment]
Usage and readme are fine with this, they don't import ./methods/saveCookiesToDisk.ts or loadCookiesToDisk

**Comment by evilive3000** [comment]
Yeah, you are right, they are ok. Just seen it.

**Comment by gladiatortoise** [comment]
I can merge this as 2.0.0.

**Comment by evilive3000** [comment]
So do you want me to return those methods or you will bump major version?

**Comment by gladiatortoise** [comment]
the latter is fine

**Pull request merged**
